project:
  type: website
  output-dir: docs

website:
  title: "MODEL EVALUATION TOOL"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "MET_operational"
        href: MET_operational.qmd
      - text: "Glossary"
        href: glossary.qmd


  sidebar:
    - title: "Home"
      contents: 
        - index.qmd
    - title: "MET_operational"
      contents: 
        - MET_operational.qmd
    - title: "Glossary"
      contents: 
      - glossary.qmd
      
format:
  html:
    theme: cosmo
    page-layout: article
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
    toc: true

glossary:
  path: glossary.yml
  popup: click
  show: true

editor: visual

