project:
  type: website
  output-dir: docs

website:
  title: "MODEL EVALUATION TOOL"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      

  sidebar:
    - title: "Home"
      contents: 
        - index.qmd
   

format:
  html:
    theme: cosmo
    page-layout: article
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true
    toc: false

editor: visual